server:
  forward-headers-strategy: NATIVE
  servlet:
    context-path: /api
    encoding:
      enabled: true
      force: true
      charset: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true